### ISSUE TITLE
eigen documentation

### ISSUE THREAD

**Issue by cernoch** [master-keying/mks#10]
The `eigen` class is practically undocumented.

**Comment by horenmar** [comment]
Some things missing documentation

* Method parameters.
  * What does `reduce` do?
  * What does `duplic` do?
  * What is a good approximation for `k`?
  * etc
* Practical differences between the algorithms
  * What kind of lock-charts are best solved by bi-clustering, versus SAT solving, versus ...
* What does `get_eigen_*` actually return and how to reconstruct the diagonal lock-chart from this
  * At a glance, a non-boundary value means that it is part of the diagonal, but having the docs say so would be nice. Also having a saner interface.

There are also probably other things, but this is a good start.

**Comment by horenmar** [comment]
The arguments for `get_eigen_key(lock)` and `get_eigen_lock(key)` seem to be mixed up. `get_eigen_key` indexes into `m_key`, which is a vector of values for key links, thus the argument should probably be called `key`. Same goes for `get_eigen_lock`.

**Comment by cernoch** [comment]
ad `get_eigen_key` / `get_eigen_lock`) I agree. From my limited experience, the names really seem to be swapped.

Marek, can you confirm?

**Comment by kryskmar** [comment]
Yes. I did the tests and the arguments in get_eigen_key / get_eigen_lock should be swapped. It is easiest fix because it should influence only validator() function.

**Comment by cernoch** [comment]
The `validator()` is not the only client of `get_eigen_*`. Tests and most importantnly, Martin's code in the `dev-condenser` branch.

Let's close this bug, resolve #24, make this a PR and let Martin merge the PR after he adapts his code.
