### ISSUE TITLE
scheduler_test.cpp needs cleanup

### ISSUE THREAD

**Issue by horenmar** [master-keying/mks#13]
Commit cb2d07da5b4aa4884a2b37943c4e4d4f7357a264, [specifically line 61](https://github.com/master-keying/mks/blob/cb2d07da5b4aa4884a2b37943c4e4d4f7357a264/src/test/cpp/scheduler_test.cpp#L61) broke scheduler_test.cpp completely.

I hotfixed it in 302bde1, but the empty `SECTION` needs better fix later.

**Comment by cernoch** [comment]
Fixed in 42d5bba.
