### ISSUE TITLE
eigen does not initialize sol_size on some paths

### ISSUE THREAD

**Issue by horenmar** [master-keying/mks#14]
Test on Windows fail because `sol_size` is equal to `0xCCCC...`. This means that it was not initialized, because `0xCCCC...` is used by Windows debug mode to signalize uninitialized stack memory.

**Comment by cernoch** [comment]
For whatever reason, `solution_size()` is not the “size of the solution”. Instead, `solution_size_reduce()` should be used.

Fixed in fc09f122b6a9981f926ed5c8ddd71609912ff084.

We should really work on issue #10.
