### ISSUE TITLE
Review needed for eigen changes

### ISSUE THREAD

**Issue by horenmar** [master-keying/mks#15]
I've started work on eigen cleanup via changes that keep local semantics the same, but result in cleaner code. The start is in two commits, 7c6c09f25416ccce21b92951fffb243163f3f4f3 and 2479d29585a86b5648290985014f7268df9fbeba, and will continue in a separate branch `dev-eigen-cleanup`.

The idea is to clean up the code to make reasoning easier (and also fix some horrible performance bugs in the process), but since the tests are broken and documentation is missing, the changes could use a review and a second set of eyes.

**Comment by cernoch** [comment]
Marek started to work on this issue yesterday. I'd be a good idea to collaborate.

Also, bare in mind that `eigen` is rather experimental:
- The purpose of this class is to test algorithms quickly and improve on those, which look promising.
- Perhaps we can simply delete the algorithms, which are “not the way to go”. It'd be faster than to polish them. :-)
- The code might be needed to support experiments in a future paper.

**Comment by cernoch** [comment]
On today's meeting with Marek, the commits looked OK to us. I'd say they're approved. :-)

**Comment by cernoch** [comment]
What's still remaining to do:
* Add tests with more locks than keys to activate more `if` branches.
* Move the `std::cout << ...` code into `eigencli` using a callback.

**Comment by cernoch** [comment]
Marek, please review the `dev-eigen-clean-up` branch.

The more changes get committed to the `master` branch, the more difficult a merge becomes.
