### ISSUE TITLE
eigen::max_matching_solver_tree on a diagonal instance

### ISSUE THREAD

**Issue by cernoch** [master-keying/mks#16]
The first test in [`eigen_test.cpp`](https://github.com/master-keying/mks/blob/6149d2f73f88ca03c4b656a1ffd724910278bb7e/src/test/cpp/eigen_test.cpp) performs a simple test – finding all individual keys in a diagonal lock-chart. However, the `eigen::max_matching_solver_tree` algorithm fails to do so. The test has been disabled, but it can be activated by uncommenting lines below:
https://github.com/master-keying/mks/blob/6149d2f73f88ca03c4b656a1ffd724910278bb7e/src/test/cpp/eigen_test.cpp#L126

Marek, is it a bug? Or merely an inefficiency in the algorithm's design?

**Comment by kryskmar** [comment]
Yes, it was bug. Wrong return value.
commit bad8f42d87555093be36a83118bcda82d5cb4a64
