### ISSUE TITLE
Travis build succeeds even if binaries do not compile

### ISSUE THREAD

**Issue by cernoch** [master-keying/mks#21]
Commit 0e44b1d6f1251e1342255a60b8657e1eed2bd818 is funny:
- The tests can be compiled and all of them pass successfully.
- Some CLI binaries can't be compiled (deprecated API).

Nevertheless, Travis shows the build as passing:
https://travis-ci.org/master-keying/mks/jobs/352932468

Is this a bug or a feature?

**Comment by horenmar** [comment]
This is a weird-ass interaction between multi-line travis yaml commands and return codes.

Figured out a fix, gonna commit it to master soon.
