### ISSUE TITLE
Set of added keys in the satpiler is not reliable

### ISSUE THREAD

**Issue by cernoch** [master-keying/mks#29]
**Reproduce:**
- https://github.com/master-keying/mks/tree/strange-bug
- run tests with the `satpiler::lock_consumed3` argument. 

What's really strange: In `satpiler::add_lock`, the `add_interaction` receives two arguments:
- The first is apparently a random piece of memory and
- the second is a valid lock.

**Key question:** Where does the random piece of memory come from?
- I've tried debugging. And `sat.kvs.m_indexes.m_dense_vals` really contains expected values.
- I've tried logging (see the patch). And the console really contains expected values.
- And still, the `add_interaction` function receives garbage.

**Comment by horenmar** [comment]
Interestingly, this is not just a random miscompilation -- I can reproduce it on both MSVC and Clang.

**Comment by cernoch** [comment]
Fixed in 71d6edabaeddf10ab0b10e56fae5f5e8fe3945ff.
