### ISSUE TITLE
(CR+)LF mismatch

### ISSUE THREAD

**Issue by cernoch** [master-keying/mks#3]
Git is confused. Are we using LF or CR+LF? What is the proper way of setting up Git?

**Comment by horenmar** [comment]
The repository used not to enforce anything, so there were files with both in-repo.

The generally accepted way is to use LF in-repo and autoconvert EOL on checkout (so a checkout originating on Windows will get files with CRLF, on Linux will get LF) and the current `.gitattributes` should be set up to enforce this except for specific files that are better off kept with specific EOL encoding (e.g. runnable .sh and .py files, as Linux kernel is unable to deal with hashbang ending in CRLF).


Files are only converted during specific actions, but once all of them are converted, the problems should not reappear (until a checkout across the file conversion boundary).

**Comment by cernoch** [comment]
Let's close this. What's the conclusion?

Should Windows or Linux developers set `core.autocrlf` to a non-default value?

**Comment by horenmar** [comment]
In general yes, but mks repository has `.gitattributes` file that forces `core.autocrlf` to `true` for the repository, no matter what is the global setting.

**Comment by cernoch** [comment]
Great!
