### ISSUE TITLE
SAT/satpiler performance regression 

### ISSUE THREAD

**Issue by cernoch** [master-keying/mks#5]
During the introduction of CMake, the performance test for SAT (`satpiler::performance`) has been slowed down by **650%**.

**Platform:** Ubuntu 16.04

**How to reproduce:**
```bash
git checkout eff5c64
rm -rf build && mkdir build && cd build
cmake .. && make -j tests
time ./tests 'satpiler::performance'
```
Result:
```
===============================================================================
All tests passed (4 assertions in 1 test case)


real	0m44.639s
user	0m44.470s
sys	0m0.052s
```

**Expected behavior:**
```bash
git checkout 74890ad
make -j target/binary/test/satpiler_test.bin WITH_REST=1
time target/binary/test/satpiler_test.bin 'satpiler::performance'
```
Result:
```
===============================================================================
All tests passed (4 assertions in 1 test case)


real	0m5.869s
user	0m5.846s
sys	0m0.020s
```

**Comment by horenmar** [comment]
Quick look says that MiniSat used to be unconditionally compiled with optimizations, now it follows the rest of the project.

Easy enough to fix.

**Comment by cernoch** [comment]
Is it a good idea to build MiniSat without optimizations, even in Debug mode?

I'd argue against it, because:
- MiniSat is rarely debugged. During my initial development, I've never needed to debug it.
- This project is focused on performance, not stability. Quick prototyping is main activity here. Since MiniSat takes 99% of CPU time, it is quite handy to save time even when playing with the code.
- If a newcomer builds this project, he should have ~90% of the performance. (This may also be tackled by a BIG WARNING in the build instructions).

Any more ideas?
